### PR TITLE
[REVIEW] TSNE Notebook

### PR DESCRIPTION
**Pull request by danielhanchen**
Hey!!

So I've written a TSNE Notebook showing off cuML's TSNE implementation :) It has many plots / graphics etc! Hope it's going to be part of the repo!

### CODE REVIEW

**Comment by taureandyernv** [comment]
Hey @danielhanchen, I'll test it out this weekend.  Very excited to see what you did!

**Comment by cjnolet** [comment]
Marking this as WIP until https://github.com/rapidsai/cuml/pull/682 is reviewed and merged.

**Comment by cjnolet** [comment]
@taureandyernv, TSNE was just merged so this notebook should be good to review.

**Comment by cjnolet** [comment]
@danielhanchen this notebook is wonderful!

I will try to provide feedback early next week, as I will be traveling tomorrow and next week is burn down. 

I’m excited to see your blog.

**Comment by danielhanchen** [comment]
@cjnolet  No problems and also thanks! Take your time :)
Yep I'll focus on the blog for now :)

**Comment by cjnolet** [comment]
It looks like this got merged in without a full review. This notebook is going to need some work to prep it for release. 

@danielhanchen, though I think the content in your t-sne demo notebook will help you get a blog together, this notebook is overly complicated and provides too much detail to be maintainable across releases. 

I have opened a WIP PR to update a bunch of our demo notebooks and plan to reduce the complexity of the t-sne notebook so that it follows more closely to the style of the other notebooks (specifically, using the fashion mnist dataset as we have done in the UMAP notebook).

**Comment by danielhanchen** [comment]
Oh ok ye I made the notebook a bit too detailed. I can probs shrink it to what the other cuml notebooks look like

**Pull request merged**
