### PR TITLE
[WIP] added documentation for several key steps

### PR DESCRIPTION
**Pull request by paulhendricks**
This pull request updates the documentation for the E2E notebook.

### CODE REVIEW

**Comment by ayushdg** [comment]
@paulhendricks Could you update the README.md file with the updated dataset link. This would address #116 in addition to #119.

**Comment by taureandyernv** [comment]
@paulhendricks , is this ready for review, or is it still WIP?

**Comment by taureandyernv** [comment]
@paulhendricks i gotta clean up the PRs.  Did a more recent PR solve the mortgage notebook issues?  Or Should i close this one?

**Comment by paulhendricks** [comment]
Let's close this, I think the mortgage notebook is changing so I'm not sure how relevant these changes are.

**Pull request closed without merging**
