### PR TITLE
[REVIEW] Coordinate descent notebook 

### PR DESCRIPTION
**Pull request by Salonijain27**
Added a new notebook containing the lasso and elastic net algorithms

### CODE REVIEW

**Comment by taureandyernv** [comment]
Still to do doc updates for:

- [ ] DBSscan

- [ ] KNN

- [ ] Linear Reg

- [ ] Ridge reg

**Comment by taureandyernv** [comment]
@Salonijain27 , can you please review my changes and format as you please.  when done, let me know what's left and if it ready to merge!

**Comment by taureandyernv** [comment]
@Salonijain27 is this PR ready to merge?

**Comment by Salonijain27** [comment]
This PR is ready to be merged

**Pull request merged**
