### PR TITLE
[REVIEW] Adding graph example notebook

### PR DESCRIPTION
**Pull request by BradReesWork**
Added the Overlap Coefficient to the old Jaccrad notebook, renamed the notebook, and did some cleanup

### CODE REVIEW

**Comment by BradReesWork** [comment]
Added Similarity (Jaccard and Overlap), Weighted Jaccard, and PageRank

**Comment by taureandyernv** [comment]
just for transparent documentation's sake:

- in Vertex Similarity, i get an attribute error.  Please fix it 
```# How many vertices are in the graph?  Remember that Graph is zero based
G.num_vertices()
# How many vertices are in the graph?  Remember that Graph is zero based
G.num_vertices()```
---------------------------------------------------------------------------
```AttributeError                            Traceback (most recent call last)
<ipython-input-10-db973b39753c> in <module>
      1 # How many vertices are in the graph?  Remember that Graph is zero based
----> 2 G.num_vertices()

AttributeError: 'Graph' object has no attribute 'num_vertices'```

- For pagerank, please create a "non pip install" version for Notebooks core.  Let's take this current version, and put it in Notebooks Extended as Pagerank Full.  Also, please add these "pip install " lines to cell #1
```# This automatically time every cell's execution
!pip install community
!pip install networkx
!pip install ipython-autotime
%load_ext autotime```

- Louvain notebook, it was odd seeing "found 4 partition" in cell 11.  let's change the print statement to
```print(str(len(part_ids)) + " partitions found")```

- In the Weighted Jaccard and Pagerank, it would be cool to get just a quick understanding/purpose of why i should use these with our dataset.

Please let me know when you have completed these changes.  Awesome notebooks, as always!

**Comment by BradReesWork** [comment]
I am not sure why `G.num_vertices()` is not working.  That function has been in cuGraph since 0.6 

Removed the use of NetworkX from the PageRank notebook
Fixed syntax errors

**Comment by taureandyernv** [comment]
@BradReesWork , @Salonijain27 and I will be testing this today with the new nightlies!  I'll be messaging you concerning the outcomes soon!

**Pull request merged**
