### PR TITLE
[REVIEW] Adding knn demo cuml notebook back into a dask_cuml directory

### PR DESCRIPTION
**Pull request by cjnolet**
This was removed for some reason. Note that this knn_demo is different than the knn_demo notebook that lives within the cuml directory.

### CODE REVIEW

**Comment by dantegd** [comment]
for organization purposes to not blow up the number of folders, wouldn't it be better to have the `dask-cuml` folder under `cuml`? Otherwise its at least 3 extra folders in the repo root

**Comment by cjnolet** [comment]
I believe the fix for the dask-cuda issue is to install an older (0.7 or before) version of the conda package. This notebook should be ready to merge.

**Comment by cjnolet** [comment]
Looking back over this notebook, it needs some markdown work in order to introduce the cells. I will try to get to this next week.

**Comment by cjnolet** [comment]
Closing this. Will get notebook together for dask-cuml k-means. dask-knn notebook should be added back when we release MNMG KNN.

**Pull request closed without merging**
